### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tyanyu0614** [tyanyu0614/furima-31671#9]
自身のフリマアプリのURL
https://furima-31671.herokuapp.com/

Basic認証のIDとパスワード
ID admin
pass 2222

出品者用のメールアドレスとパスワード
test@test2
qqqqqq1

購入者用のメールアドレスとパスワード
test@test3
qqqqqq1

購入用カードの番号・期限・セキュリティコード
4242424242424242
1/23
123

**Comment by jaragit** [comment]
堀端さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・ログアウト状態のユーザーは、URLを直接入力して商品購入ページに遷移しようとすると、商品の販売状況に関わらずログインページに遷移すること
→購入済み、未購入の状態どちらもログインページに行かず、エラーが発生しました。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A
ログアウト状態のユーザーは、URLを直接入力して商品購入ページに遷移しようとすると、商品の販売状況に関わらずログインページに遷移すること

**Comment by tyanyu0614** [comment]
ご指摘頂いた点、修正させていただきましたので
ご確認お願いいたします。

**Comment by jaragit** [comment]
堀端さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
